version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - 127.0.0.1:9200:9200

  web:
      build: ./web
      links:
        - elasticsearch
        - rabbitmq
      environment:
        - NODE_VERSION=5.0.0
        - NPM_VERSION=3.3.6

  worker:
      build: ./worker
      links:
        - elasticsearch
        - rabbitmq
      environment:
        - NODE_VERSION=5.0.0
        - NPM_VERSION=3.3.6

  rabbitmq:
     image: rabbitmq
     ports:
      - 0.0.0.0:5672:5672
     environment:
      - RABBITMQ_DEFAULT_USER=ocr
      - RABBITMQ_DEFAULT_PASS=secret_pass


